name: testplugin171
main: io.github.d0048.riding.IoGithubD0048Riding
version: beta
description: This is my first plugin for environment testing.
author: HXB
commands: 
    addtoplayerlist:
        description: 添加玩家到游戏中
        usage: /<command>
        permission: <plugin name>.basic
        permission-message: You don't have <permission></source> </code> </blockquote> 