name: ShellController
main: shellcontroller.ShellController
version: beta
description: This is a plugin to control the computer.
author: HXB
commands: 
    exec:
        description: 执行一条命令并且获取输出
        usage: /<command> [command]
        permission: shellcontroller.op
        permission-message: 你没权限。。别试了