Game_World: 
Explode_Size: 5
TNTdelay: 1
Wall_Size_X: 3
Wall_Size_Y: 3
Shield_Delay: 1
Shield_Hold: 6
amountBeacon: 1
amountBed: 1
amountBow: 1
amountArrow: 1
amountBread: 1
amountTNT: 1
amountIronSward: 1